### ISSUE TITLE
Update for 1.18.1?

### ISSUE THREAD

**Issue by Lord-Memester** [flier268/MoreTooltips#3]
Incredibly useful mod, and I can't find any that do the same thing. Would be super happy to see it get updated. Hopefully, you haven't abandoned the mod.

Really love it! Hoping for an update in the near future, but as long as it gets updated within a reasonable amount of time, I'll be smiling wide.

Please update it!

**Comment by flier268** [comment]
Release [v1.1.0](https://github.com/flier268/MoreTooltips/releases/tag/v1.1.0)
