### ISSUE TITLE
[Suggestions] Some more tooltip ideas

### ISSUE THREAD

**Issue by Zartrix** [flier268/MoreTooltips#4]
Hey, I just found your mod and had some ideas for some more possible tooltips:
- [Composting chance](https://minecraft.fandom.com/wiki/Composter#Composting) though this one might be a bit harder
- [Light level](https://minecraft.fandom.com/wiki/Light#Light-emitting_blocks) pretty straight forward

Let me know if you're considering them or even adding them!

**Comment by flier268** [comment]
c6e31c2434bd3fa1ad1e9ff87168becb647cf482
