### ISSUE TITLE
use single translation entries instead of manually building string

### ISSUE THREAD

**Issue by Linguardium** [flier268/MoreTooltips#5]
https://github.com/flier268/MoreTooltips/blob/master/src/main/java/com/flier268/more_tooltips/TooltipEventHandler.java#L142

This can more easily be done with a single entry. TranslatableText can take variables such as %d to provide decimal in the text:

"translation.key" : "The Number: %d" 

new TranslatableText("translation.key", 3);

This means you need 1 translation entry instead of 2, and you dont need to manually build the texts using 3 lines

**Comment by flier268** [comment]
Thank you, @Linguardium
